/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hanfak' at '12/1/16 6:26 PM' with Gradle 2.13
 *
 * @author hanfak, @date 12/1/16 6:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
